### PR TITLE
WSS-612 Updates CertificateStore to handle certificate chains.

### PR DESCRIPTION
**Pull request by coyotesqrl**

### CODE REVIEW

**Comment by coheigea** [comment]
Why was this changed?

-                        new TrustAnchor(cert, cert.getExtensionValue(NAME_CONSTRAINTS_OID));
+                        new TrustAnchor(cert, null);

**Comment by coyotesqrl** [comment]
The change makes more sense within the context of #6, but this is because the default Sun PKIX Path Validator does not support Name Constraints on Trust Anchors and will throw an InvalidAlgorithmParameterException if they are provided. Other implementations may also be unsafe.

Even in that change this is incomplete in this class as it provides no means to the user to affirmatively pass Name Constraints to the Test Anchor for part Validator implementations that do support Name Constraints. That option has only been implemented for the Merlin and MerlinAKI crypto implementations so far.

**Comment by coheigea** [comment]
When you say that " That option has only been implemented for the Merlin and MerlinAKI crypto implementations so far." - how exactly is this done?

**Comment by coyotesqrl** [comment]
This conditional check in `addTrustAnchors` (https://github.com/apache/wss4j/pull/6/files#diff-284168913220d0d86204648514548d43R1424) in `Merlin` is the branching logic. It is set here (https://github.com/apache/wss4j/pull/6/files#diff-284168913220d0d86204648514548d43R202) based on a new property.

The affirmative test that a path Validator can handle a Trust Anchor with Name Constraints was the only reasonable way I could find to handle the conditional logic. Otherwise, it would not fail until long after the set of Trust Anchors had been constructed, when it was processed by the path Validator. Any dynamic solution I could conceive involved performing a validation check, catching the potential exception, and then rerouting back to rebuild all the Trust Anchors.

**Comment by coheigea** [comment]
Ah right thanks. I was a bit confused by your comment, I thought you were referring to existing code in WSS4J.

**Comment by coheigea** [comment]
Could you add the new property in for CertificateStore as well (defaulting to allowing NAME_CONSTRAINTS_OID) as part of this patch? I don't really want to change the current logic for 2.1.x.

**Comment by coyotesqrl** [comment]
The original issue we had encountered was that the `NameConstraints` extension was being extracted from the certificate and passed directly to the `TrustAnchor` constructor without first decoding the DER-encoded octet string. That failed, with the `TrustAnchor`'s ctor throwing an `IllegalArgumentException` caused by the invalid encoding of the NameConstraintsExtension. Only after fixing that did I discover the secondary issue where Sun's default PKIX path validator does not accept Trust Anchors with included Name Constraints.

The issue directly resolved in this PR, where `CertificateStore` does not traverse up certificate chains, was only found as a side-effect of the unit tests written for #6.

If I update the code in this patch with the new property - or simply change line 227 back to `new TrustAnchor(cert, cert.getExtensionValue(NAME_CONSTRAINTS_OID));` - then any processing logic that goes down this path will throw the `IllegalArgumentException`. Nulling that out gets past the problem and also doesn't trigger that second issue with the Sun PKIX path validator.

#6 resolves the both of the Name Constraints problems for Merlin/MerlinAKI and can be easily updated to use the property for `CertificateStore` as well.

I'll take any measures you see fit for this PR and the other; I just feel strange about fixing the certificate chain traversal but leaving the known bug with Name Constraint extraction/Trust Anchor construction here.

**Comment by coheigea** [comment]
OK thanks for the explanation - that seems reasonable to me for this issue.

**Pull request closed without merging**
