### PR TITLE
added support for a comma-separated list of crl and issuer DN constraint

### PR DESCRIPTION
**Pull request by clibois**
added support for a comma-separated list of crl

### CODE REVIEW

**Comment by clibois** [comment]
I have missed the change of the error code into failedCredentialLoad. Need to be changed

**Comment by clibois** [comment]
I have added a support to define a constraint on the issuer DN name such as:
<entry key="sigIssuerCertConstraints" value=".*SIGN.*"/> << sample from a cxf endpoint
I'm working with Intellij and use the Eclipse Formatter plugin. I took the default format from eclipse Mars. If you still have problem with indent please export your format configuration.

**Comment by clibois** [comment]
hum attempt to fix indentation didn't work. Will wait for your formatter profile then.

**Comment by clibois** [comment]
I have tried with the cxf formatter but that gave me a different format style... So I have removed manualy every extra indent outside the code I have changed.

**Comment by coheigea** [comment]
Could you create a separate PR for the Issuer DN stuff and just have this PR for the CRL issue please? Also, the Issuer DN patch has lots of whitespace changes still in it.

**Comment by clibois** [comment]
Ok I will try to revert it.
For the issuer DN patch I didn't see any extra indent problem. Maybe that
in the code I have done there are some indent problem but now with
untouched code. Please note that I have added 2 files too.
Best Regards,

2016-10-11 12:02 GMT+02:00 coheigea <notifications@github.com>:

**Comment by coheigea** [comment]
There are indent problems, such as:

-                    && publicKey.equals(((X509Certificate)certs[0]).getPublicKey())) {
+                        && publicKey.equals(((X509Certificate)certs[0]).getPublicKey())) {

**Comment by clibois** [comment]
Oops sorry I gorget to use the force parameter to push to reset. Now you should only have 1 file changed(Merlin).

**Pull request closed without merging**
